from rest_framework import status

STATUS_SUCCESS = 200  # 성공
STATUS_USER_PERMISSION_ERROR = 4001
STATUS_USER_DOES_NOT_EXISTS = 4002
STATUS_USER_EMAIL_ALREADY_EXISTS = 4003
STATUS_USER_NOT_MATCHED = 4004
STATUS_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR  # 서버가 처리 방법을 모르는 상황이 발생

MSG_RSP_SUCCESS = '성공'
MSG_RSP_PERMISSION_ERROR = '유저 접근 권한이 없습니다.'
MSG_RSP_USER_DOES_NOT_EXISTS = '이미 존재하는 유저입니다.'
MSG_RSP_USER_EMAIL_ALREADY_EXISTS = '동일한 이메일이 존재합니다.'
MSG_RSP_USER_NOT_MATCHED = '아이디 혹은 비밀번호를 확인해주세요.'

code_to_alert = {
    STATUS_SUCCESS: MSG_RSP_SUCCESS,
    STATUS_USER_PERMISSION_ERROR: MSG_RSP_PERMISSION_ERROR,
    STATUS_USER_DOES_NOT_EXISTS: MSG_RSP_USER_DOES_NOT_EXISTS,
    STATUS_USER_EMAIL_ALREADY_EXISTS: MSG_RSP_USER_EMAIL_ALREADY_EXISTS,
    STATUS_USER_NOT_MATCHED: MSG_RSP_USER_NOT_MATCHED,
}


def code_to_message(code):
    return code_to_alert.get(code)
